export const ADD_BLOCK_REQUEST = 'ADD_BLOCK_REQUEST';
export const ADD_BLOCK_SUCCESS = 'ADD_BLOCK_SUCCESS';
export const ADD_BLOCK_FAILURE = 'ADD_BLOCK_FAILURE';
export const GET_BLOCK_REQUEST = 'GET_BLOCK_REQUEST';
export const GET_BLOCK_SUCCESS = 'GET_BLOCK_SUCCESS';
export const GET_BLOCK_FAILURE = 'GET_BLOCK_FAILURE';
export const CLOSE_ERROR = 'CLOSE_ERROR';
